name: "Set up dev environment"
description: "Sets up asdf & configure the cache"
runs:
  using: composite
  steps:
    - name: asdf setup
      uses: asdf-vm/actions/setup@v1
    - uses: actions/checkout@v3
    - name: install tools
      shell: bash
      run: |
        cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
        asdf plugin-update --all
        asdf reshim
        pip install -r requirements.txt
        asdf reshim
    - uses: actions/cache@v3
      id: asdf-cache
      with:
        path: |
          ~/.asdf
        key: ${{ runner.os }}-asdf-cache-${{ hashFiles('.tool-versions') }}
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ~/.cache/yarn
          ./test-react-app/node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('test-react-app/yarn.lock') }}-v1
    - name: update submodules
      run: git submodule update --init
      shell: bash
